"""AddLikeColumnForShortsAndVideoTable

Revision ID: 2da3825d734e
Revises: fe354d042519
Create Date: 2025-06-09 21:59:42.070656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da3825d734e'
down_revision: Union[str, None] = 'fe354d042519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shorts', sa.Column('like_cnt', sa.BIGINT(), server_default='0', nullable=True))
    op.add_column('Shorts', sa.Column('dislike_cnt', sa.BIGINT(), server_default='0', nullable=True))
    op.add_column('Video', sa.Column('like_cnt', sa.BIGINT(), server_default='0', nullable=True))
    op.add_column('Video', sa.Column('dislike_cnt', sa.BIGINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Video', 'dislike_cnt')
    op.drop_column('Video', 'like_cnt')
    op.drop_column('Shorts', 'dislike_cnt')
    op.drop_column('Shorts', 'like_cnt')
    # ### end Alembic commands ###
