"""UpdateShortsEntity

Revision ID: 48f41cac7329
Revises: e29caf322760
Create Date: 2025-07-08 14:24:10.393578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f41cac7329'
down_revision: Union[str, None] = 'e29caf322760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shorts', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Shorts', 'user_id')
    # ### end Alembic commands ###
