"""UpdateUserColumnByPhone

Revision ID: 4bdff4559510
Revises: eca03e4f1b48
Create Date: 2025-04-29 17:49:30.379437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bdff4559510'
down_revision: Union[str, None] = 'eca03e4f1b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone_is_validation', sa.SMALLINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'phone_is_validation')
    # ### end Alembic commands ###
