"""FixVideoCommentLikeTable

Revision ID: 7759f14f1d6a
Revises: 07afd0502312
Create Date: 2025-06-29 18:48:27.885899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7759f14f1d6a'
down_revision: Union[str, None] = '07afd0502312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VideoCommentLike', sa.Column('video_id', sa.Integer(), nullable=True))
    op.drop_column('VideoCommentLike', 'shorts_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VideoCommentLike', sa.Column('shorts_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('VideoCommentLike', 'video_id')
    # ### end Alembic commands ###
