"""AddSubscription

Revision ID: 840bd99c8041
Revises: d2a9b384b48e
Create Date: 2025-07-01 14:53:17.793434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840bd99c8041'
down_revision: Union[str, None] = 'd2a9b384b48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VideoSubscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('VideoComment', sa.Column('is_fixed', sa.SMALLINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VideoComment', 'is_fixed')
    op.drop_table('VideoSubscription')
    # ### end Alembic commands ###
