"""UpdateUserColumnByEmail

Revision ID: c865d5df1095
Revises: 4bdff4559510
Create Date: 2025-05-01 21:18:48.711280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c865d5df1095'
down_revision: Union[str, None] = '4bdff4559510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('email_validation_number', sa.String(length=10), nullable=True))
    op.add_column('User', sa.Column('email_is_validation', sa.SMALLINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'email_is_validation')
    op.drop_column('User', 'email_validation_number')
    # ### end Alembic commands ###
