"""FixVideoCommentTable

Revision ID: d2a9b384b48e
Revises: 7759f14f1d6a
Create Date: 2025-06-29 18:54:06.873929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a9b384b48e'
down_revision: Union[str, None] = '7759f14f1d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VideoComment', sa.Column('like_cnt', sa.BIGINT(), server_default='0', nullable=True))
    op.add_column('VideoComment', sa.Column('dislike_cnt', sa.BIGINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VideoComment', 'dislike_cnt')
    op.drop_column('VideoComment', 'like_cnt')
    # ### end Alembic commands ###
