"""AddLikeCntByShortsCommentTable

Revision ID: d86fe8191e20
Revises: 16330ca21f2a
Create Date: 2025-06-16 14:45:43.354201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86fe8191e20'
down_revision: Union[str, None] = '16330ca21f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ShortsComment', sa.Column('like_cnt', sa.BIGINT(), server_default='0', nullable=True))
    op.add_column('ShortsComment', sa.Column('dislike_cnt', sa.BIGINT(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ShortsComment', 'dislike_cnt')
    op.drop_column('ShortsComment', 'like_cnt')
    # ### end Alembic commands ###
