"""AddProfileAndNicknameForUserTable

Revision ID: e2a0a5b79c4c
Revises: d86fe8191e20
Create Date: 2025-06-16 15:00:19.425764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a0a5b79c4c'
down_revision: Union[str, None] = 'd86fe8191e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('profile_image', sa.String(length=255), nullable=True))
    op.add_column('User', sa.Column('nickname', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'nickname')
    op.drop_column('User', 'profile_image')
    # ### end Alembic commands ###
