"""AddUserColumnByPhone

Revision ID: eca03e4f1b48
Revises: 46226ba4be0a
Create Date: 2025-01-16 19:55:11.337943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca03e4f1b48'
down_revision: Union[str, None] = '46226ba4be0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone_number', sa.String(length=40), nullable=True))
    op.add_column('User', sa.Column('phone_validation_number', sa.String(length=10), nullable=True))
    op.add_column('User', sa.Column('phone_send_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'phone_send_at')
    op.drop_column('User', 'phone_validation_number')
    op.drop_column('User', 'phone_number')
    # ### end Alembic commands ###
