"""AddTagForVideoTableAndShortsTable

Revision ID: fe354d042519
Revises: 6c4b7d4f5e9a
Create Date: 2025-06-05 19:57:00.155832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe354d042519'
down_revision: Union[str, None] = '6c4b7d4f5e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Shorts', sa.Column('tag', sa.String(length=20), nullable=True))
    op.add_column('Video', sa.Column('tag', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Video', 'tag')
    op.drop_column('Shorts', 'tag')
    # ### end Alembic commands ###
