# This is a basic workflow to help you get started with Actions

name: Deploy prod eb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: |
          pip install awsebcli --upgrade --user
          pip install virtualenv
          virtualenv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Create config.json and .zip file
        run: |
          echo '{"APP_PORT": 8000, "APP_MODE": "production", "AES256_KEY": "${{ secrets.FASTAPI_AES256_KEY }}", "DB_USER_NAME": "${{ secrets.FASTAPI_DB_USER_NAME }}", "DB_USER_PASSWD": "${{ secrets.FASTAPI_DB_USER_PASSWD }}", "DB_HOST": "${{ secrets.FASTAPI_DB_HOST }}", "DB_NAME": "${{ secrets.FASTAPI_DB_NAME }}", "SECRET": "${{ secrets.FASTAPI_SECRET }}", "GOOGLE_CLIENT_ID": "17027771141-013lhjhd887gda8seu1f0dbeet0bllkp.apps.googleusercontent.com", "GOOGLE_SECRET_ID": "${{ secrets.FASTAPI_GOOGLE_SECRET_ID }}", "KAKAO_CLIENT_ID": "eec1a6ee6dcc81867bfb2375006dbdef", "GITHUB_CLIENT_ID": "Ov23liz4lNHVSl9wrBEB", "GITHUB_SECRET_ID": "${{ secrets.FASTAPI_GITHUB_SECRET_ID }}"}' > config.json
          zip -r fastapi-prod-${{ github.run_id }}-${{ github.run_attempt }}.zip . -x '*.git*'

      - name: Deploy Consumer to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.FASTAPI_EB_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.FASTAPI_EB_SECRET_KEY }}
          wait_for_deployment: false
          application_name: fastapi
          environment_name: fastapi-env
          region: ap-northeast-2
          version_label: fastapi-prod-${{ github.run_id }}-${{ github.run_attempt }}
          deployment_package: fastapi-prod-${{ github.run_id }}-${{ github.run_attempt }}.zip
